version: '3'

services:
  econofoods:
    build:
      context: ./econofoods
    container_name: econofoods1
    volumes:
      - ./econofoods:/var/www/html/econofoods/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    external_links:
      - dbmysql
    networks:
      - dbmysql_network
  fitness:
    build:
      context: ./fitnessp
    container_name: fitness1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fitnessp:/fitness
    ports: 
      - "8000:8000"
    networks:
      - dbmysql_network
  myphpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myphpmyadmin1
    ports:
      - "8082:80"
    environment:
       PMA_HOST: dbmysql
    networks:
      - dbmysql_network
  dbmysql:
    image: mysql
    container_name: dbmysql
    volumes:
      - ./mysql/my/custom:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: root
    networks:
      - dbmysql_network
networks:
  dbmysql_network:
    external: true
